#!/bin/sh
# fq10
readonly tempDirectory=/mnt/ramdisk/
readonly urlQueue=${tempDirectory}mq
readonly urlQueueHist=${tempDirectory}q_hist
readonly playerDefaultArgs='--pause --keep-open --really-quiet'
readonly youtubeDlDefaultArgs='--no-part --youtube-skip-dash-manifest --no-call-home --no-playlist'
tryResume=0

downloadMedia(){
	local url=$1
	echo 'Downloading' $url
	[ $tryResume -eq 1 ] && echo 'Resuming from previous.'
	case "$url" in
		*.youtube.com/watch?v=*)
			downloadYoutube $url
		;;
		*.crunchyroll.com/*)
			downloadStreamlink $url
		;;
		*)
			echo 'No url matches'
			return 1
		;;
	esac
	return 0
}

downloadYoutube(){
	local url=$1
	youtube-dl -F $url > ${tempDirectory}formats
	getYoutubeFmts ${tempDirectory}formats
	if [ $? -eq 0 ]
	then
		downloadYoutubeFmt $url $vfmt ${tempDirectory}1
		sleep 10
		downloadYoutubeFmt $url $afmt ${tempDirectory}1aud
		sleep 20
	fi
}
getYoutubeFmts(){
	local lines=$1
	vfmt=$(findVideoFmtCode ${ext='webm'} ${vres=240} $lines)
	afmt=$(findAudioFmtCode ${abr=80} $lines)
	if [ $vfmt -eq 0 ]
	then
		echo 'Video not availiable in resolution.'
		return 1
	fi
	if [ $afmt -eq 0 ]
	then
		echo 'Audio not availiable in bitrate.'
		return 1
	fi
	return 0
}
findAudioFmtCode(){
	local best=0 desired=$1 lines=$2 code=0 line
	while IFS= read -r line
	do
		local abr=$(echo $line | egrep 'DASH audio\s+[0-9]+k' -o | egrep '[0-9]+' -o)
		if [ -n "$abr" ] && [ "$abr" -le "$desired" ] && [ $abr -gt $best ]
		then
			best=$abr
			code=$(echo $line | cut -f 1 -d ' ')
		fi
	done < $lines
	echo $code
}
findVideoFmtCode(){
	local bestRes=0 bestFmt=0 desiredCodec=$1 desiredVRes=$2 lines=$3 line
	while IFS= read -r line
	do
		echo $line | egrep $desiredCodec'\s+[0-9]' -o > /dev/null
		if [ $? -eq 0 ]
		then
			local res=$(echo $line | egrep '[0-9]+x[0-9]+\s+[0-9]+p' -o | tr -s ' ' | cut -d ' ' -f 2)
			if [ -n "$res" ]
			then
				res=$(echo $res | egrep '[0-9]+' -o)
				if [ "$res" -le "$desiredVRes" ] && [ "$res" -gt "$bestRes" ]
				then
					bestRes=$res
					bestFmt=$(echo $line | cut -f 1 -d ' ')
				fi
			fi
		fi
	done < $lines
	echo $bestFmt
}
downloadYoutubeFmt(){
	local url=$1 fmt=$2 to=$3
	[ $tryResume -eq 0 ] && overwriteVidBuf $to ${to}old
	echo "Download started for fmt $fmt"
	youtube-dl -q $youtubeDlDefaultArgs -r ${speed=32K} -f $fmt $url -o $to &
}
overwriteVidBuf(){
	# Overwrites filename 2nd arg at ${tempDirectory} with 1st arg
	[ -f $1 ] && mv -f $1 $2
}

addQueueUrl(){
	[ -n "$1" ] && echo $1 >> $urlQueue
}

getQueueUrl(){
	read -r url < $urlQueue
}
popQueueUrl(){
	sed -i '1d;/^$/d' $urlQueue
}

viewMedia(){
	echo Viewing media
	[ -s ${tempDirectory}1aud ] && dash=--audio-file=${tempDirectory}1aud
	[ -s ${tempDirectory}1 ] && mpv $playerDefaultArgs ${tempDirectory}1 $dash &
}


handleHist(){
	case "$1" in
		see|'')
			cat $urlQueueHist
		;;
		add)
			addQueueUrl $(getHistUrl)
		;;
		resume)
			url=$(getHistUrl)
			if [ -n "$url" ]
			then
				echo 'Resuming from history.'
				tryResume=1
				cmd='dl'
			fi
		;;
	esac
}
getHistUrl(){
	[ -s $urlQueueHist ] && echo $(tail -n 1 $urlQueueHist)
}


addToHist(){
	[ -z "$1" ] && return
	local last
	[ -s $urlQueueHist ] && last=$(getHistUrl)
	[ $last != $1 ] && echo $1 >> $urlQueueHist
}


cmd=$1
case "$cmd" in
	'')
		getQueueUrl
		if [ -n "$url" ] 
		then
			popQueueUrl
			cmd='dl'
		fi
	;;
	resume)
		tryResume=1
		if [ $# -gt 1 ]
		then
			url=$2
		else
			getQueueUrl
			[ -n "$url" ] && popQueueUrl
		fi
		[ -n "$url" ] && cmd='dl'
	;;
	add)
		addQueueUrl $2
	;;
	get)
		getQueueUrl
		[ -n "$url" ] && popQueueUrl && echo $url
	;;
	top)
		getQueueUrl
		[ -n "$url" ] && echo $url
	;;
	flush)
		> $urlQueue
		echo 'Queue flushed.'
	;;
	see)
		cat $urlQueue
	;;
	view)
		viewMedia
	;;
	hist)
		handleHist $2
	;;
	*)
		url=$1
		cmd='dl'
	;;
esac
if [ "$cmd" = 'dl' ]
then
	addToHist $url
	downloadMedia $url && viewMedia
fi

