#!/bin/sh
d=/mnt/ramdisk/
q=${d}mq
player_args='--pause --keep-open --really-quiet'
rss_feeds=~/.newsbeuter/urls
yt_def_args='--no-part --youtube-skip-dash-manifest --no-call-home --no-playlist'

alias err_beep='beep -f 100 -d 500 -r 2'
alias player='mpv'
alias pp='[ -f ${d}1 ] && mv -f ${d}1 ${d}0'
alias streamlink='~/.local/bin/streamlink'
alias youtube-dl='~/.local/bin/youtube-dl'

dash_tube(){
	[ $# -eq 0 ] && return 1
	[ $# -eq 1 ] && pp
	echo Downloading at vq = ${vquality=242} and aq = ${aquality=250} at s = ${speed=25K}
	youtube-dl $yt_def_args -r $speed -f $vquality $1 -o ${d}1 &
	sleep 10
	[ -f ${d}1aud ] && mv -f ${d}1aud ${d}0aud
	youtube-dl $yt_def_args -q -r $speed -f $aquality $1 -o ${d}1aud &
	sleep 20
	player $player_args ${d}1 --audio-file ${d}1aud
	return 0
}

nx(){
	# Gets top of the top. Pops it unless there's an 1st argument.
	read -r L < $q
	echo $L
	[ $# -eq 0 ] && sed -i '1d;/^$/d' $q
}
streamlink_dl(){
	# Usage: streamlink_dl URL [RESM]
	# Requires atleast 1 argument.
	[ $# -eq 0 ] && return 1
	[ $# -eq 1 ] && pp
	echo Downloading at q = ${squality=240p}
	streamlink $1 ${squality} -o ${d}1 &
	sleep 30
	return 0
}
streamlink_stream(){
	# Usage: streamlink_stream URL
	# Requires exactly 1 argument.
	[ $# -eq 0 ] && return 1
	echo Streaming at ${squality=240p}
	streamlink -p 'mpv --title="streamlink player"' --player-no-close --player-passthrough hls $1 ${squality}
}
try_play(){
	# Plays last video downloaded.
	if [ -s ${d}1 ]
	then
		player $player_args ${d}1 &
	else
		err_beep
	fi
}
yt_dl(){
	# Usage: yt_dl URL [RESM]
	# Requires atleast 1 argument.
	[ $# -eq 0 ] || [ -s ${d}lfile ] && return 1
	touch ${d}lfile
	[ $# -eq 1 ] && pp
	echo Downloading at q = ${quality=36} and s = ${speed=40k}
	youtube-dl $yt_def_args -r $speed -f $quality $1 -o ${d}1 || err_beep &
	sleep 30
	rm ${d}lfile
	return 0
}

if [ $# -gt 0 ]
then
	case "$1" in
		add)
			[ $# -eq 1 ] && echo `xclip -o` >> $q || echo $2 >> $q
		;;
		cr) # no 2nd arg, use q.
			streamlink_stream $([ -z $2 ] && nx || echo $2)
		;;
		top)
			nx KEEP
		;;
		dt)
			dash_tube $([ -z $2 ] && nx || echo $2)
		;;
		F)	# get possible quality
			# if no 2nd arg, use q.
			youtube-dl $yt_def_args -F $([ -z $2 ] && nx || echo $2)
		;;
		fls)
			> $q
		;;
		go)
			yt_dl $2 && try_play
		;;
		halt)
			[ -n $(pgrep youtube-dl) ] && killall youtube-dl
		;;
		plunge)
			[ -f ${d}lfile ] && rm ${d}lfile
		;;
		resm)
			yt_dl $([ -z $2 ] && nx || echo $2) RESM && try_play
		;;
		see)
			cat $q
		;;
		sets)
			echo dash- use speed=X then export
			echo fish- use set -x speed
		;;
		sl)
			streamlink_dl $([ -z $2 ] && nx || echo $2) && try_play
		;;
		view)
			player $player_args ${d}1 &
		;;
		subscribe)
			l=$([ $# -gt 1 ] && echo $2 || xclip -o)
			if [ -n $l ]
			then
				echo $l >> $rss_feeds
				echo Added $l to $rss_feeds
			fi
		;;
		xc)
			yt_dl $(xclip -o) && try_play
		;;
	esac
else
	# If lfile exists: play. otherwise: play depending on whats on q
	if [ -f ${d}lfile ]
	then
		player $player_args ${d}1
		rm ${d}lfile
	else
		url=`nx`
		[ -z $url ] && exit 1
		case "$url" in
			*.youtube.com/watch?v=*)
				yt_dl $url && try_play
			;;
			*.crunchyroll.com/*)
				streamlink_stream $url
			;;
			*)
				echo $url
				echo Option not recognized or q is empty.
				echo $url >> $q
			;;
		esac
	fi
fi
