#!/bin/sh
tempDirectory=/mnt/ramdisk/
urlQueue=${tempDirectory}mq
urlQueueHist=${tempDirectory}q_hist
playerDefaultArgs='--pause --keep-open --really-quiet'
youtubeDlDefaultArgs='--no-part --youtube-skip-dash-manifest --no-call-home --no-playlist'
tryResume=0


hist_add(){
	if [ -s $urlQueueHist ]
	then
		last=$(tail -n 1 $urlQueueHist)
		[ $last = $1 ] && return 0
	fi
	echo $1 >> $urlQueueHist
}
nx(){
	# Gets top of the top. Pops it unless there's an 1st argument.
	read -r url < $urlQueue
	[ $# -eq 0 ] && sed -i '1d;/^$/d' $urlQueue
}
arg_or_xclip(){
	[ $# -gt 0 ] && echo $1 || xclip -o 2> /dev/null
}
set_url(){
	# Sets url to either $1 or whatever on the queue.
	[ $# -gt 0 ] && url=$1 || [ -s $urlQueue ] && nx
	[ -z $url ] && exit 1
	echo 'URL:' $url
}
set_url_ax(){
	# Given an arglist, set URL if possible.
	# Sets url to either $1 or whatever on the xclipboard.
	# Special case if $url was 'hist' in which set_url_hist is used.
	url=`arg_or_xclip $@`
	[ "$url" = 'hist' ] && set_url_hist
	[ -z "$url" ] && [ -s $urlQueue ] && exit 1
	echo 'URL:' $url
}
set_url_hist(){
	# Set $url to last line of hist file if it exists.
	[ -s $urlQueueHist ] || exit 1
	url=`tail -n 1 $urlQueueHist`
}
need_resume(){
	# Sets $tryResume if needed.
	if [ "$1" = 'r' ]
	then
		resume=1
		echo 'Resuming download..'
		return 0
	else
		return 1
	fi
}
view_file(){
	[ -s ${tempDirectory}1aud ] && dash=--audio-file=${tempDirectory}1aud
	[ -s ${tempDirectory}1 ] && player $playerDefaultArgs ${tempDirectory}1 $dash &
}
overwrite_f(){
	# Overwrites filename 2nd arg at ${tempDirectory} with 1st arg
	[ -f ${tempDirectory}$1 ] && mv -f ${tempDirectory}$1 ${tempDirectory}$2
}
youtube_f_get(){
	# Uses $url $tryResume
	# Args are 1-fmt 2-speed 3-suffix
	[ $tryResume -eq 0 ] && overwrite_f 1${3} 0${3}
	echo 'Downloading format:' $1 'and s =' $2
	youtube-dl $youtubeDlDefaultArgs -r $2 -f $1 $url -o ${tempDirectory}1${3} &
}
youtube_dash(){
	# Downloads both video and audio dash versions.
	# Uses $url $tryResume
	hist_add $url
	youtube_f_get 'bestvideo[height<='${vres=240}'][ext=webm]' ${speed=32K}
	sleep 10
	if [ ! -s ${tempDirectory}1 ]
	then
		echo 'Could not get video data.'
		exit 1
	fi
	youtubeDlDefaultArgs='-q '$youtubeDlDefaultArgs
	# Next call to youtube_f_get is quiet
	printf '\n'
	youtube_f_get 'bestaudio[abr<='${abr=85}']' ${aspeed=32K} aud
	sleep 20
	view_file
}
streamlink_dl(){
	# Uses $: url tryResume
	[ $tryResume -eq 0 ] && overwrite_f 1 0 && overwrite_f 1aud 0aud
	hist_add $url
	echo 'Downloading at q =' ${squality=240p}
	streamlink $url ${squality} -o ${tempDirectory}1 &
	sleep 30
}
streamlink_stream(){
	# Uses $: url
	hist_add $url
	echo 'Streaming at' ${squality=240p}
	streamlink -p 'mpv --title="streamlink player"' --player-no-close --player-passthrough hls $url ${squality}
}
if [ $# -gt 0 ]
then
	case "$1" in
		add)
			shift
			set_url_ax $@
			if [ -n $url ]
			then
				echo 'Added to queue.'
				echo $url >> $urlQueue
			fi
		;;
		top)
			nx KEEP
			echo $url
		;;
		get)
			nx
			echo $url
			hist_add $url
		;;
		fls)
			> $urlQueue
			echo 'Queue flushed.'
		;;
		see)
			cat $urlQueue
		;;
		view)
			view_file
		;;
		halt)
			killall youtube-dl
			echo 'youtube-dl killed.'
		;;
		hist)
			cat $urlQueueHist
		;;
		ytd)
			# (resume-able)
			shift
			need_resume $1 && shift
			set_url_ax $@
			youtube_dash
		;;
		sls)
			shift
			set_url_ax $@
			streamlink_stream
		;;
		sld)
			# (resume-able)
			shift
			need_resume $1 && shift
			set_url $@
			streamlink_dl && view_file
		;;
		*)
			echo 'Arguments not recognized'
			echo $@
		;;
	esac
else
	#echo Options were: $@
	set_url $@
	# Will only grab from queue since $1 will be blank.
	case "$url" in
		*.youtube.com/watch?v=*)
			youtube_dash
		;;
		*.crunchyroll.com/*)
			streamlink_stream
		;;
	esac
fi
